package io.github.titaniumcoder.reporting.client

import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotBlank
import javax.validation.constraints.Size

class Client {
    // Unique, 10 chars, not blank
    @NotBlank
    var id: String = ""

    // max 100 chars, not blank
    @NotBlank
    @Size(max = 100)
    var name: String = ""

    // can be whatever there is, max 255 chars
    @Size(max = 255)
    var notes: String? = null

    // must be bigger than 0 and smaller than 5260320 (10 years)
    @Min(0)
    @Max(5260320)
    var maxMinutes: Int? = null

    // must be between 0 and 200000
    @Min(0)
    @Max(200000)
    var rateInCentsPerHour: Int? = null
}

class Project {
    // autogenerated
    var id: Long = 0L

}
