language: java
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app: kotlin-reporting
  api_key:
    secure: mzcHY5oyprFbzQmlD51gmGVfYERu0kViyiBaKzNWUMswHEzgegf0nwMs7i/BRQOgbcs+J/vs2b4ih1ZmSrO3QV+jnfEBT8Q4E782JI5LM9mfsXzqmLVpO/EqXg3E1CaY7NLX9X0XrGtFGFbYmgGqS3Ss9uDEPNXKjMjg17GgNi8HuyT0np54P6/lMSt7mFHWLfRVLedr3UkszsR4DF789NQKZdqBT2XRar5q6JAig4PiagGd6TDMmjCbTFZry7oeb/8+u7eP6qB5baEnAHvBxXeq+/VjE0vlTYukHChRXn1A75Z20WMqHpE4QkjBPLEwjPGdAJWLbNE2q8avWfjNrmMVjFFS/m9kKBjhufRdPgCAdj2rmv7c5nsWu8Kt8ZkWQ7Z9L4kQwx+VR5GFO/UtuVg6fLfYh5gBfw34XO0SfqxCot2MjfhCZl3ZTyhro/ZN7XzYFhU690keaR6E/jGIisUAN4ucspL/kwCpZONj3XsYWC55rACJsiWUg2mW4YMpYDNgvoNv75KjupITvFjjdQmgktMvyJizcfmNNebuAj5vW7DiAp77W4lBsk/BvIOIVftpJkv5d26wISvxR6HFaHDr7FyUkYJhRDiNd+2vik4AabLlLZWeTmnEeFsbauv2lDlz9bU6GAnX5GNfeaEmrOU4uZAg+RQXFvULAoDZgDM=
