language: java

addons:
  sonarcloud:
    organization: "titaniumcoder-github"

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
  - sonar-scanner
after_success:
  - bash < (curl -s https://codecov.io/bash)
