language: java
install: true

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

# services: postgresql

os: linux
jdk: openjdk11
dist: trusty

env:
  global:
    - PGPORT=5433
    - CI=true

before_script:
  - psql -c 'create database rtest;' -U postgres


script:
  - ./gradlew assembleServerAndClient --scan -s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/dists/
