language: java
script:
- "./gradlew check"
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: T62aTdWzozMhsF5Y4wKP8yMGF2zsx++SB7+corg0sPs24oHFimNZ60dkjRcV3UzYRNE9trmVd4HVLz3r5rxXA5nBQT/gygrrlAgfu5eQgF5WQzZ2N+CyJVDQYVm5ApvMaq1qJnhRJuJR7OGYNb73ocVsSX5JYehi8RKCF/7DN72dkRagyqTis9bxwsZ3sMByggVUtCKTSBBNfsmKSoMrx2R3BsNADxTrO7o00DDwR/lGNFaBtmZmARg7EAqhHX06VA6KVsRzA0tcIXliYZ3aIxKuwzbRPOBwfdUMUfqP//+jM2eGXp+VHrwh2OI9iNtYOXNZ0NAuUQFxKxg3PZaizT06CpueNL4vwTskamVngTRAjf++En2TEuzz0/TAjnQgVvbgvoIH2a4WHynfa9nBaVK+h8FWcs8x3cgWEh/6T5bzjW3MK/AlIYRc0hCbEPQ/fqY60WrbXd+XIFPMzzq+EzNL+sAkBfjMxgrcikeTzaWZopxy0b/zl63KxLfNrZ+NYncLsFB6p1o8N+OTgD7xDYQf8nzFrW/RQQIDChGsN1fqsmTw+bDTPBSXTNnYLnEXUVuLDhZBagFUsf+W9YlFVH6ngpbjKQah2tA0jP9iA0IUgAEwEan9Cql6ROz4gYgJmPJcyjQxaIcKfA0CZv+9SzbthrxB0u42hM3nL4/S/qM=
  app: kotlin-reporting
