language: java
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app: kotlin-reporting
  api_key:
    secure: LN4ytQ4bO/kG9sieUibESZ/IIy8iD+7O/GAGs6AlrXsftKGYkua3huYYgqTneQuc/nu+ZiVzRUDGB6ZApAMUjAtfulm4uM4lryb5pWLRpDz6dHWzg61DYDKvus1BWPldioaObdMfKchWd2bH2ZFL3/7xXiHhecpxctWlWDMzpyWLtRU+GSAQ2leRM+Ioc4Qi03wra1J7QFW5/5NMP2nIs+W7oeileURNcDqEWXdYwKHUZkV9JudAbDS6Ky9CWBk13qIstQfBoD8h5YLhRZZazeCELoBsP1z4FaFUno5Uo/9DqxfaZ4X/6JtNroilbLJBADpV4syULh2wvZ4om7vFuc9pukhNDuQfFBpkRdk76NFxECY3iCZJ1KF7yKaD8dc13CZjRL9hG0N42u4QbYMBDi7SjdjB9mWdmnFOcB+YsSqRjAh6BQrlbhKcWzgTtSsODRsWajmy5/RGGT/m0hq28u8LRc6QbSv1IE0dx9XvtJjnItCLWwKjWfaGEwSBh3IubS1yo/J4fYSInbg8eyMHYau2VyhWWkXnmW1XEA84svR7TiIOONK/F3XXSZR4b02BlpTWKeLLOPOckY2TCoiufhFg/sBZ46JiJR6+Kh+PnU5z5njWXKLmAfMmP1ndmBxKxAZ1vOetKzvBubKUMlj0x7qfqQorzL+y3G1oyABpea8=
