apiVersion: v1
kind: Namespace
metadata:
  name: reporting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              value: reporting
          image: postgres:11.6
          imagePullPolicy: IfNotPresent
          name: db
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: reporting
spec:
  type: LoadBalancer
  ports:
    - name: db
      port: 5432
      targetPort: 5432
  selector:
    name: db
