application:
  apiToken: ${API_TOKEN}
  workspaceId: 2131925
  security:
    username: test
    password: test

spring:
  webflux.static-path-pattern: "/**"
  resources:
    static-locations:
      - classpath:static/**
  jackson.serialization.write-dates-as-timestamps: false
