application:
  apiToken: ${API_TOKEN}
  workspaceId: 2131925
  security:
    username: test
    password: test
#  router:
#    static-resources:
#      default:
#        enabled: true
#        mapping: "/**"
#        paths: "classpath:public"
