package io.github.titaniumcoder.reporting.project

import io.github.titaniumcoder.reporting.client.Client
import javax.persistence.*
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotBlank
import javax.validation.constraints.Size

@Entity
@Table(name = "project")
data class Project(
        // autogenerated
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        val id: Long? = null,

        @ManyToOne(cascade = [CascadeType.ALL])
        @JoinColumn(name = "client_id")
        val client: Client,

        val active: Boolean = true,

        @NotBlank
        @Size(max = 100)
        val name: String,

        // must be bigger than 0 and smaller than 5260320 (10 years)
        @Min(0)
        @Max(5260320)
        @Column(name = "max_minutes")
        val maxMinutes: Int? = null,

        // must be between 0 and 200000
        @Min(0)
        @Max(200000)
        @Column(name = "rate_in_cents_per_hour")
        val rateInCentsPerHour: Int? = null,

        @Column(name = "billable")
        val billable: Boolean = true
)

data class ProjectDto(
        val id: Long?,

        val clientId: String,
        val clientName: String,

        val active: Boolean,
        val billable: Boolean,

        val name: String,

        val maxMinutes: Int?,

        val rateInCentsPerHour: Int?,

        val minutesUsed: Int,
        val minutesRemaining: Int?,
        val minutesPercentage: Double?,
        val amountBilled: Double,
        val amountOpen: Double,
        val amountRemaining: Double?
)
