micronaut:
  application:
    name: reporting
  security:
    enabled: false
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          openid:
            issuer: 'https://accounts.google.com'
    endpoints:
      logout:
        get-allowed: true
    intercept-url-map:
      -
        pattern: /ui/**
        access:
          - isAuthenticated()
      -
        pattern: /
        access:
          - isAuthenticated()
  router:
    static-resources:
      react:
        enabled: true
        paths: classpath:static
        mapping: /**
mongodb:
  uri: mongodb+srv://reporting:zdpo9pk765JvfAHx@reporting.bkqix.mongodb.net/<dbname>?retryWrites=true&w=majority
---
