micronaut:
  application:
    name: toggl-reporting
  server:
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
  security:
    enabled: true
    intercept-url-map:
      -
        pattern: /api/login
        access:
          - isAnonymous()
      -
        pattern: /api/**
        access:
          - isAuthenticated()
      -
        pattern: /**
        http-method: GET
        access:
          - isAnonymous()
    endpoints:
      login:
        enabled: true
        path: /api/login
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${TOGGL_SECRET}
  io:
    watch:
      paths: src/main
      restart: true
---
application:
  apiToken: ${API_TOKEN}
  workspaceId: ${WORKSPACE_ID}
  security:
    username: ${APPLICATION_SECURITY_USERNAME}
    password: ${APPLICATION_SECURITY_PASSWORD}
    secret: ${TOGGL_SECRET}
    expiration: 28800
---
jackson:
  locale: 'de-CH'
  dateFormat: 'yyyy-MM-dd'
  timeZone: 'Europe/Zurich'
  serializationInclusion: ALWAYS
  serialization:
    writeDatesAsTimestamps: false

---
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full
server:
  port: ${PORT:8080}
