micronaut:
  application:
    name: toggl-reporting

  server:
    cors:
      enabled: true

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

  security:
    enabled: true
    intercept-url-map:
      -
        pattern: /api/*
        access:
          - isAuthenticated()
    endpoints:
      login:
        enabled: true
        path: "/api/login"
      oauth:
        enabled: true
    token:
      basic-auth:
        enabled: false
      jwt:
        enabled: true
        signature:
          secret:
            generator:
              secret: justSomeThingForLater

  io:
    watch:
      paths: src/main
      restart: true

endpoints:
  info:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: true
  health:
    enabled: true
    sensitive: false
  refresh:
    enabled: true
    sensitive: true
  environment:
    enabled: true
    sensitive: true
  stop:
    enabled: true
    sensitive: true

toggl:
  apiToken: ${API_TOKEN:api-token}
  workspaceId: 2131925
  username: test
  password: test

#spring:
#  jackson.serialization.write-dates-as-timestamps: false
