application:
  apiToken: ${API_TOKEN}
  workspaceId: ${WORKSPACE_ID}
  username: ${USERNAME}
  password: ${PASSWORD}
  security:
    secret: ${TOGGL_SECRET}
    expiration: 28800

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full

