micronaut:
  application:
    name: reporting
  security:
    oauth2:
      clients:
        google:
          client-secret: ???
          client-id: 483387557047-olrn4mkp6m7gltp5fqhgr76094q6qf6e.apps.googleusercontent.com
          openid:
            issuer: https://accounts.google.com
    reject-not-found: true
    enabled: false
mongodb:
  uri: mongodb+srv://reporting:zdpo9pk765JvfAHx@reporting.bkqix.mongodb.net/<dbname>?retryWrites=true&w=majority
---
