spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://db:5432/reporting}
    username: ${JDBC_USER:reporting}
    password: ${JDBC_PASSWORD:""}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:

        client-id: 483387557047-olrn4mkp6m7gltp5fqhgr76094q6qf6e.apps.googleusercontent.com
        client-secret: ${GOOGLE_SECRET}
me:
  url: "https://www.googleapis.com/userinfo/v2/me"
