spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://db:5433/reporting}
    username: ${JDBC_USER:reporting}
    password: ${JDBC_PASSWORD:""}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
  cache:
    type: caffeine
    cache-names: tokens
    caffeine:
      spec: maximumSize=100,expireAfterAccess=60s # TODO may be optimize later
  #    type: none

reporting:
  clientId: 483387557047-olrn4mkp6m7gltp5fqhgr76094q6qf6e.apps.googleusercontent.com
  clientSecret: ${GOOGLE_SECRET}
  adminEmail: rico.metzger@gmail.com

