micronaut:
  application:
    name: toggl-reporting

  server:
    cors:
      enabled: true

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

  security:
    enabled: true
    intercept-url-map:
      -
        pattern: /api/*
        access:
          - isAuthenticated()
      - pattern: /**
        access:
          - isAnonymous()
    endpoints:
      login:
        enabled: true
        path: "/api/login"
      oauth:
        enabled: true
    token:
      basic-auth:
        enabled: false
      jwt:
        enabled: true
        signature:
          secret:
            generator:
              secret: justSomeThingForLater

  io:
    watch:
      paths: src/main
      restart: true

endpoints:
  info:
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  health:
    enabled: true
    sensitive: true
  refresh:
    enabled: true
    sensitive: true
  environment:
    enabled: true
    sensitive: true
  stop:
    enabled: true
    sensitive: true

datasources:
  default:
    url: jdbc:postgresql://db:5432/reporting
    username: reporting
    password: ""
    driverClassName: org.postgresql.Driver
