# TODO
#  security:
#    enabled: true
#    intercept-url-map:
#      -
#        pattern: /api/*
#        access:
#          - isAuthenticated()
#      - pattern: /**
#        access:
#          - isAnonymous()

spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://db:5432/reporting}
    username: ${JDBC_USER:reporting}
    password: ${JDBC_PASSWORD:""}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
