version: 2
jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx1g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
# Preparation for the later release with budget overview
#      - image: circleci/postgres:12-alpine
#        environment:
#          POSTGRES_USER: postgres
#          POSTGRES_DB: circle_test
    steps:
      - checkout
# TODO add client test and everything!
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - restore_cache:
          key: v1-server-gradle-cache-{{ checksum "server/build.gradle" }}
      - restore_cache:
          key: v1-client-node-modules-{{ checksum "client/package.json" }}
      - run:
          name: Run tests
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~/server/.gradle/caches
          key: v1-server-gradle-cache-{{ checksum "server/build.gradle" }}
      - save_cache:
          paths:
            - ~/client/node_modules
          key: v1-client-node-modules-{{ checksum "client/package.json" }}
      - store_test_results:
          path: server/build/test-results/test
      - store_artifacts:
          path: server/build/test-results/test
          when: always
      - run:
          name: Assemble JAR
          command: |
            # Skip this for other nodes
            if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
              ./gradlew assembleServerAndClient
            fi
      - store_artifacts:
          path: server/build/libs

workflows:
  version: 2
  workflow:
    jobs:
      - build
