package io.github.titaniumcoder.reporting.user

import io.github.titaniumcoder.reporting.project.Project
import java.time.LocalDateTime
import javax.validation.constraints.Size

data class TimeEntry(
        // Autogenerated
        val id: Long?,

        val starting: LocalDateTime,
        val ending: LocalDateTime?,
        val project: Project?,

        @Size(max = 200)
        val description: String?,

        val user: User,

        val billable: Boolean = true,
        val billed: Boolean = false
)

data class TimeEntryDto(
        val timeEntry: TimeEntry
)
