package io.github.titaniumcoder.reporting.user

import io.github.titaniumcoder.reporting.client.Client
import io.github.titaniumcoder.reporting.project.ProjectDto
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotBlank
import javax.validation.constraints.Size

data class User(
        // Autogenerated
        val id: Long?,

        @NotBlank
        @Size(max = 100)
        val username: String,

        @Size(max = 100)
        val password: String?,

        val canBook: Boolean = true,
        
        val canViewMoney: Boolean = true,

        val admin: Boolean = true,

        val clients: List<Client> = listOf()
)

data class UserDto(
        val user: User
)
